# docker-compose.yml
version: "3"

services:
  backend:
    restart: always
    container_name: omsu_qr_back
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    environment:
      MYSQL_DATABASE: \${MYSQL_DATABASE}
      MYSQL_USER: \${MYSQL_USER}
      MYSQL_PASSWORD: \${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: \${MYSQL_ROOT_PASSWORD}

    volumes:
      - ./backend:./backend
    ports:
      - 8000:8000

  frontend:
    restart: always
    container_name: omsu_qr_front
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:./frontend
    ports:
      - 3000:3000
  db:
    image: mysql:5.7
    restart: always
    container_name: omsu_qr_db
    environment:
      MYSQL_DATABASE: \${MYSQL_DATABASE}
      MYSQL_USER: \${MYSQL_USER}
      MYSQL_PASSWORD: \${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: \${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./backend/data:/var/lib/mysql
